name: Unity Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Cache Unity
      - name: Cache Unity
        uses: actions/cache@v3
        with:
          path: ~/.local/share/unity3d
          key: unity-${{ runner.os }}-${{ hashFiles('**/Packages/manifest.json') }}

      # Setup Unity Editor
      - name: Setup Unity
        uses: game-ci/unity-builder@v2
        with:
          version: 2021.3.28f1  # Replace with your Unity version
          targetPlatform: StandaloneWindows64  # Adjust based on your build target

      # Build Unity project
      - name: Build project
        uses: game-ci/unity-builder@v2
        with:
          version: 2021.3.28f1 
          targetPlatform: StandaloneWindows64
          projectPath: .

      # Upload the build as an artifact
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Build
          path: build/StandaloneWindows64
